language: node_js
deploy:
  provider: npm
  email: npmjs@solsort.com
  api_key:
    secure: hxGS6bAq2Y4/mBr3XvX0y5fRM7VCZ5oGUARc2T5v0yj5dsutz1+kN3F0Mbo0bUUPhKoWeo9aoSJeYCtb61SuLFNEyA1AZG7oJ0bPUzQUrogf9baZuT9/Dce787QjrPmP4ewSPoqG17FHebVJ1wSeYV8Od7rDnG37G3yINqfkPqClwCMaPZoSDPZ+ffOPTCIMSfVCF6cCGdNgMO3XYlIJo4D7kFJxlOMmh0mNQO3wBDOwGZltwhoDn/IDwtfwaQe7MlATN1cMs1aQixTXPLqRnXaqtZOG1mQcm/+pznooIqABcegTeboRXIoCpeweBj5Egwq50h6OlDlaRMvU0RWCnXMqs45mYNQIFxEAbhg4OFh86jGeSGpuEUdp7KK6AEV76ymepcRqhHjkvnu7q3nu1RW5FENTe6VdEbtMt1vW0YynUSfFHmeiimXNLNxune6pEMCIW9K2I8rCc85dmyk8h6dtVtSzVwFNdE8UnXeVV8VyuveZcuGbIncEqlpM3qde0w52+KLCD1I9GUjc6a68uXrkkbonZb7PQo2SczQpOrylesmAS/e1dlONgjrEbQlAqu7/BirxDDT4LK35BfMOqrdffRwxQpijsHbUtC4gZzbSSg4l0ZkC9T7OKe1IrtUQG0sSIuEdcbQmaziI3u8WDNaf3VDnT5w4XovJ+1WsnOo=
  on:
    repo: solsort/solsort
